# Startup
exec-once = hyprpaper
exec-once = hypridle
exec-once = ags run "$HOME/.config/ags/app.tsx" --log-file /tmp/ags.log
exec-once = systemctl --user start hyprpolkitagent
exec-once = dunst
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# This start in waybar
exec-once = fcitx5 -d
exec-once = nm-applet --indicator
exec-once = dbus-update-activation-environment --systemd --all

exec-once = hyprctl --batch "dispatch moveworkspacetomonitor 3 desc:AOC 24B15H3 AP15536R03560 ; dispatch moveworkspacetomonitor 2 desc:AOC 24B15H3 AP15536R03516 ; dispatch moveworkspacetomonitor 1 desc:Shenzhen KTC Technology Group H27T22S 0x00000001 ; dispatch focusmonitor desc:AOC 24B15H3 AP15536R03560 ; dispatch workspace 3; dispatch focusmonitor desc:AOC 24B15H3 AP15536R03516 ; dispatch workspace 2 ; dispatch focusmonitor desc:Shenzhen KTC Technology Group H27T22S 0x00000001 ; dispatch workspace 1"
# Shutdown
exec-shutdown = cliphist wipe
