windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
# windowrule = content none, match:class ^(mpv)$



# -----------------------------------------------------
# ZALO / BOTTLES FIXES (Hyprland v0.53+ Syntax)
# -----------------------------------------------------

# 1. Force the Main Zalo window to TILE
# windowrule {
#     name = zalo-tiling
#
#     # Matching conditions
#     match:class = steam_proton
#     match:title = Zalo
#
#     # Effect to apply
#     tile = true
# }
#
# # 2. Banish the "Ghost" Tray Window off-screen
# windowrule {
#     name = banish-zalo-ghost
#
#     # Match the Proton wrapper class AND an Empty Title (^$)
#     match:class = steam_proton
#     match:title = ^$
#
#     # Effects to apply
#     float = true
#     no_focus = true
#     no_initial_focus = true
#     move = -2000 -2000
# }

windowrule {
    name = fullscreen-Genshin

    match:class = ^(genshinimpact.exe)$

    fullscreen = true
    render_unfocused = true

}
