source = ~/.config/hypr/hypr_conf/Startup_and_Shutdown/*
source = ~/.config/hypr/hypr_conf/Appearance/*
source = ~/.config/hypr/hypr_conf/Environment_var/*
source = ~/.config/hypr/hypr_conf/IO/*
source = ~/.config/hypr/hypr_conf/Windows_and_Workspace/*
source = ~/.config/hypr/hypr_conf/Functionality/*
source = ~/.config/hypr/hypr_conf/Bind/*
